### ISSUE TITLE
Move utility functions to `util.py`

### ISSUE THREAD

**Issue by amsehili** [amsehili/genRSS#32]

**Comment by BasDeGamer** [comment]
Do you mean all functions but the main function?

**Comment by amsehili** [comment]
Hi @BasDeGamer,
Right. If you want to contribute it, please do not forget to run the tests to make sure everything is OK:

```
python genRSS.py --run-tests
```

**Comment by BasDeGamer** [comment]
I moved the code, and there are no errors in VSC, but when I run the test command you provided I do not get any output.

I am really new to this, and I'm sorry if the solution is something really obvious.

**Comment by amsehili** [comment]
> EDIT: I found out the test uses doctest, and the article I found states that the type of test you used usually doesn't provide any output unless it failed.

As mentioned in my comment o PR, you can use `-v` for verbose mode.

**Comment by amsehili** [comment]
Closed by #40.

**Comment by BasDeGamer** [comment]
I think I understand how the testing works. I will look into pytest tomorrow. I assume we manually need to make a correct RSS 2.0 file, and then compare the program against it. If so, I will also need to look into RSS 2.0, because I don't know what it is or what it does yet.
