### ISSUE TITLE
Use pytest instead of doctest for testing

### ISSUE THREAD

**Issue by amsehili** [amsehili/genRSS#35]

**Comment by BasDeGamer** [comment]
I think I understand how the testing works. I will look into pytest tomorrow. I assume we manually need to make a correct RSS 2.0 file, and then compare the program against it. If so, I will also need to look into RSS 2.0, because I don't know what it is or what it does yet.

**Comment by denilsonsa** [comment]
What would be the benefit of getting rid of the doctests? If there isn't enough benefit, it's probably better/easier to keep them instead.

**Comment by amsehili** [comment]
We can keep them as they're part of the documentation. The title (original: *Get rid of doctests, use pytest*)  can be confusing as the goal is to rely on pytest rather then doctest for testing.

**Comment by amsehili** [comment]
Fixed by 8e94515316b6d1dfdbc673ade75f9d09bc1091ab.
