### ISSUE TITLE
require mutagen?

### ISSUE THREAD

**Issue by maphew** [amsehili/genRSS#44]
Are there particular reasons to not simply make [mutagen ](https://mutagen.readthedocs.io/en/latest/) a requirement instead of optional?

Mutagen is cross platform and has no dependencies outide of the python standard library. Guaranteeing it's available would simplify setup process as well as the Readme doc. The change is very straightforward:

```
diff --git a/pyproject.toml b/pyproject.toml
index f2b7a5e..bb6caf1 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -5,5 +5,7 @@ requires = ["setuptools", "wheel"]
 name = "genRSS"
 version = "0.2.0"

+dependencies = ["mutagen"]
+
 [project.scripts]
 genRSS = "genRSS:main"
```

**Comment by amsehili** [comment]
Now `mutagen` and `eyed3` are installed automatically.
See commit 9decb5a7f07cfa167c2f5e8f7c1c8b16c4469101.
