### ISSUE TITLE
Feeds should not be served with the "application/x-rss+xml" media type

### ISSUE THREAD

**Issue by snakekick** [amsehili/genRSS#7]
hello and thanks for the fantastic script.
my litte problem is proberly only a usage fault.
when i generate a rss the -t / --title parameter work in the 
"  <channel>
     <title>xxxx</title>" field
but under 
    <item>
 <title>xxxx.extension</title>" field
the script add the extension from the file what starts my problem.

is there a easy solution for this problem ?
thanks

**Comment by snakekick** [comment]
ok another problem are the "&" in filename
a friend help me but i don´t know how to update here the sourcecode so i write in the comment

import string

   #string.replace(Variable, zu ersetzender Wert, Ersetzung)
    title = string.replace(title, '&', 'and')
    #Die letzten vier Zeichen (Dateiendung) aus dem Titel entfernen
    title = "{0}<title>{1}</title>\n".format(indent * 3, title[0:-4])
    description = string.replace(description, '&', 'and')
    descrption = "{0}<description>{1}</description>\n".format(indent * 3, description)

thank you

**Comment by gaul** [comment]
@snakekick I proposed a solution for XML escaping.  Can you expand on the suggestion of not serving `application/x-rss+xml`?

**Comment by amsehili** [comment]
Solved by #22.
